/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSnapshot {
  'activeUsers' : bigint,
  'channelsCreated' : bigint,
  'messagesSent' : bigint,
  'storiesPosted' : bigint,
  'timestamp' : bigint,
  'totalUsers' : bigint,
  'goldVolume' : number,
}
export interface AppNotification {
  'id' : NotificationId,
  'kind' : NotificationKind,
  'read' : boolean,
  'timestamp' : Timestamp,
}
export interface Channel {
  'id' : ChannelId,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'avatarUrl' : [] | [string],
  'category' : [] | [string],
  'pinnedPostId' : [] | [ChannelPostId],
}
export type ChannelCommentId = bigint;
export interface ChannelCommentWithProfile {
  'id' : ChannelCommentId,
  'text' : string,
  'author' : UserProfile,
  'timestamp' : Timestamp,
}
export type ChannelId = bigint;
export interface ChannelPost {
  'id' : ChannelPostId,
  'content' : ChannelPostContent,
  'channelId' : ChannelId,
  'author' : UserId,
  'timestamp' : Timestamp,
}
export interface ChannelPostContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type ChannelPostId = bigint;
export interface ChannelPostInteractions {
  'likeCount' : bigint,
  'viewCount' : bigint,
  'comments' : Array<ChannelCommentWithProfile>,
  'likedByMe' : boolean,
}
export interface ChannelWithMeta {
  'ownerProfile' : UserProfile,
  'isFollowing' : boolean,
  'followerCount' : bigint,
  'channel' : Channel,
}
export type CommentId = bigint;
export interface Conversation {
  'id' : ConversationId,
  'lastMessageTimestamp' : bigint,
  'members' : Array<UserId>,
  'messages' : Array<Message>,
  'type' : ConversationType,
  'pinnedMessageId' : [] | [MessageId],
}
export type ConversationId = bigint;
export type ConversationType = { 'group' : string } |
  { 'direct' : null };
export interface DealerInfo {
  'username' : string,
  'balance' : bigint,
  'avatarUrl' : [] | [string],
}
export interface FollowerSnapshot { 'count' : bigint, 'timestamp' : bigint }
export interface GoldTransaction {
  'id' : GoldTxId,
  'timestamp' : Timestamp,
  'txType' : GoldTxType,
  'counterpartyUsername' : [] | [string],
  'amount' : bigint,
}
export type GoldTxId = bigint;
export type GoldTxType = { 'buyRequest' : null } |
  { 'sent' : null } |
  { 'claimed' : null } |
  { 'received' : null } |
  { 'sellRequest' : null };
export type MediaType = { 'audio' : null } |
  { 'other' : string } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Message {
  'id' : MessageId,
  'content' : MessageContent,
  'readReceipts' : Array<MessageReadReceipt>,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'replyTo' : [] | [ReplyToInfo],
  'reactions' : Array<UserId>,
}
export interface MessageContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type MessageId = bigint;
export interface MessageInput {
  'content' : MessageContent,
  'replyToMessageId' : [] | [MessageId],
}
export interface MessageReadReceipt {
  'userId' : UserId,
  'timestamp' : Timestamp,
}
export type NotificationId = bigint;
export type NotificationKind = {
    'goldGifted' : { 'fromUsername' : string, 'amount' : bigint }
  } |
  {
    'channelPostLiked' : {
      'channelId' : bigint,
      'byUsername' : string,
      'postId' : bigint,
    }
  } |
  {
    'channelPostCommented' : {
      'channelId' : bigint,
      'byUsername' : string,
      'postId' : bigint,
    }
  } |
  { 'storyCommented' : { 'byUsername' : string, 'statusId' : bigint } } |
  { 'storyLiked' : { 'byUsername' : string, 'statusId' : bigint } } |
  { 'channelFollowed' : { 'channelId' : bigint, 'byUsername' : string } };
export interface OnlineUser {
  'username' : string,
  'displayName' : string,
  'userId' : UserId,
  'avatarUrl' : [] | [string],
  'lastSeen' : Timestamp,
}
export interface ReplyToInfo {
  'messageId' : MessageId,
  'preview' : string,
  'senderUsername' : string,
}
export interface Status {
  'id' : StatusId,
  'content' : StatusContent,
  'author' : UserId,
  'timestamp' : Timestamp,
}
export interface StatusCommentWithProfile {
  'id' : CommentId,
  'text' : string,
  'author' : UserProfile,
  'timestamp' : Timestamp,
}
export interface StatusContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type StatusId = bigint;
export interface StatusInteractions {
  'likeCount' : bigint,
  'viewCount' : bigint,
  'comments' : Array<StatusCommentWithProfile>,
  'likedByMe' : boolean,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'lastSeen' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChannelPost' : ActorMethod<
    [ChannelId, ChannelPostContent],
    ChannelPostId
  >,
  'addGroupMember' : ActorMethod<[ConversationId, string], undefined>,
  'addMessageReaction' : ActorMethod<[ConversationId, MessageId], undefined>,
  'addStatus' : ActorMethod<[StatusContent], StatusId>,
  'adminClaimGold' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Claim 0.01 Pulse (100 units at ×10000 scale) from the charity pool once per 24 hours.
   * / A 5% platform fee is applied: pool pays 100 units, fee (5 units) is
   * / distributed proportionally to all Pulse holders, claimer receives 95 units (0.0095 Pulse).
   */
  'claimDailyCharityPulse' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'commentOnChannelPost' : ActorMethod<
    [ChannelPostId, string],
    ChannelCommentId
  >,
  'commentOnStatus' : ActorMethod<[StatusId, string], CommentId>,
  'createChannel' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    ChannelId
  >,
  'createDirectConversation' : ActorMethod<[UserId], ConversationId>,
  'createGroupConversation' : ActorMethod<
    [string, Array<UserId>, [] | [string]],
    ConversationId
  >,
  'deleteChannel' : ActorMethod<[ChannelId], undefined>,
  'deleteChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'deleteGroupName' : ActorMethod<[ConversationId], undefined>,
  'deleteHighlight' : ActorMethod<[StatusId], undefined>,
  'deleteMessage' : ActorMethod<[ConversationId, MessageId], undefined>,
  /**
   * / Donate Pulse to the charity pool. Minimum 100 units (0.01 Pulse at ×10000 scale).
   * / 5% platform fee is deducted from the donated amount and distributed
   * / proportionally to all Pulse holders. The remaining 95% enters the pool.
   */
  'donateToPulseCharity' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'editChannelPost' : ActorMethod<
    [ChannelPostId, ChannelPostContent],
    undefined
  >,
  'editMessage' : ActorMethod<[ConversationId, MessageId, string], undefined>,
  'followChannel' : ActorMethod<[ChannelId], undefined>,
  'forwardChannelPost' : ActorMethod<
    [ChannelPostId, ConversationId],
    MessageId
  >,
  'getActiveUsersCount' : ActorMethod<[], bigint>,
  'getAdminTotalClaimed' : ActorMethod<[], bigint>,
  'getAllChannels' : ActorMethod<[], Array<ChannelWithMeta>>,
  'getAllStories' : ActorMethod<[], Array<[UserProfile, Array<Status>]>>,
  /**
   * / Returns analytics snapshots filtered to the given range.
   * / Also triggers a new snapshot if more than 1 hour has passed since the last one.
   * / range: "today" | "week" | "month" | "alltime"
   */
  'getAnalyticsTrend' : ActorMethod<[string], Array<AnalyticsSnapshot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[ChannelId], [] | [ChannelWithMeta]>,
  /**
   * / Returns follower count snapshots for the given channel.
   * / Only the channel owner may call this.
   */
  'getChannelFollowerHistory' : ActorMethod<
    [ChannelId],
    Array<FollowerSnapshot>
  >,
  'getChannelPostInteractions' : ActorMethod<
    [ChannelPostId],
    ChannelPostInteractions
  >,
  'getChannelPosts' : ActorMethod<[ChannelId], Array<ChannelPost>>,
  'getChannelsByCategory' : ActorMethod<[string], Array<ChannelWithMeta>>,
  /**
   * / Returns the caller's last charity claim timestamp (null if never claimed).
   */
  'getCharityLastClaim' : ActorMethod<[], [] | [bigint]>,
  /**
   * / Returns the current charity pool balance in raw units.
   */
  'getCharityPoolBalance' : ActorMethod<[], bigint>,
  'getContactStatuses' : ActorMethod<[], Array<[UserProfile, Array<Status>]>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  'getGroupAvatars' : ActorMethod<[], Array<[ConversationId, string]>>,
  'getGroupCreators' : ActorMethod<[], Array<[ConversationId, UserId]>>,
  'getHighlights' : ActorMethod<[UserId], Array<Status>>,
  'getMessageReactions' : ActorMethod<
    [ConversationId, MessageId],
    Array<UserId>
  >,
  'getMessageReadReceipts' : ActorMethod<
    [ConversationId, MessageId],
    [] | [Array<MessageReadReceipt>]
  >,
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], Array<Message>>,
  'getMyBlockedUsers' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / Returns (channelId, currentFollowerCount) for all channels owned by the caller.
   */
  'getMyChannelFollowerCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getMyConversations' : ActorMethod<[], Array<Conversation>>,
  'getMyGoldBalance' : ActorMethod<[], bigint>,
  'getMyGoldTransactions' : ActorMethod<[], Array<GoldTransaction>>,
  'getMyNotifications' : ActorMethod<[], Array<AppNotification>>,
  /**
   * / Returns the number of times the caller's profile has been viewed.
   */
  'getMyProfileViewCount' : ActorMethod<[], bigint>,
  'getMyStatuses' : ActorMethod<[], Array<Status>>,
  'getMyTransactionHistory' : ActorMethod<[], Array<GoldTransaction>>,
  'getOnlineUsers' : ActorMethod<[], Array<OnlineUser>>,
  'getPaginatedMessages' : ActorMethod<
    [ConversationId, bigint, bigint],
    Array<Message>
  >,
  /**
   * / Returns the total number of profile views for a given userId (by username).
   */
  'getProfileViewCount' : ActorMethod<[string], bigint>,
  'getStatusInteractions' : ActorMethod<[StatusId], StatusInteractions>,
  'getStoryViewers' : ActorMethod<[StatusId], Array<string>>,
  'getStoryViewersList' : ActorMethod<[StatusId], Array<string>>,
  'getStoryViewersWithAvatars' : ActorMethod<
    [StatusId],
    Array<{ 'username' : string, 'avatarUrl' : [] | [string] }>
  >,
  'getTotalChannelsCreated' : ActorMethod<[], bigint>,
  'getTotalGoldVolume' : ActorMethod<[], number>,
  'getTotalMessagesCount' : ActorMethod<[], bigint>,
  'getTotalStoriesPosted' : ActorMethod<[], bigint>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getTypingUsers' : ActorMethod<[ConversationId], Array<string>>,
  'getUnreadCount' : ActorMethod<[ConversationId], bigint>,
  'getUserByPrincipal' : ActorMethod<[UserId], [] | [UserProfile]>,
  /**
   * / Returns a user's basic profile by username (for Online Now avatars, etc.)
   */
  'getUserByUsername' : ActorMethod<
    [string],
    [] | [
      {
        'id' : Principal,
        'username' : string,
        'displayName' : string,
        'avatarUrl' : [] | [string],
      }
    ]
  >,
  'getUserChannelsCreated' : ActorMethod<[], bigint>,
  'getUserMessageCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserStoriesPosted' : ActorMethod<[], bigint>,
  'getUsersWithGoldAbove' : ActorMethod<[bigint], Array<DealerInfo>>,
  'giftGoldToPost' : ActorMethod<
    [ChannelPostId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'giftGoldToStory' : ActorMethod<
    [StatusId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'isBlockedBy' : ActorMethod<[UserId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isHighlighted' : ActorMethod<[StatusId], boolean>,
  'isUserOnline' : ActorMethod<[UserId], boolean>,
  'leaveConversation' : ActorMethod<[ConversationId], undefined>,
  'likeChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'likeStatus' : ActorMethod<[StatusId], undefined>,
  'listUserConversations' : ActorMethod<[], Array<Conversation>>,
  'markAsRead' : ActorMethod<[ConversationId], undefined>,
  'markMessagesAsRead' : ActorMethod<[ConversationId], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  /**
   * / Pin a post in a channel.
   * / Only the channel owner may pin.
   */
  'pinChannelPost' : ActorMethod<
    [ChannelId, ChannelPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Pin a message in a conversation or group.
   * / - Direct conversations: any member may pin.
   * / - Group conversations: only the group owner (creator) may pin.
   */
  'pinMessage' : ActorMethod<
    [ConversationId, MessageId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordChannelPostView' : ActorMethod<[ChannelPostId], undefined>,
  /**
   * / Record that the caller viewed profileUserId's profile. Self-views are skipped.
   */
  'recordProfileView' : ActorMethod<[string], undefined>,
  'recordStoryView' : ActorMethod<[StatusId], undefined>,
  'removeFromHighlights' : ActorMethod<
    [StatusId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeGroupMember' : ActorMethod<[ConversationId, UserId], undefined>,
  'removeMessageReaction' : ActorMethod<[ConversationId, MessageId], undefined>,
  'requestBuyGold' : ActorMethod<[bigint], undefined>,
  'requestSellGold' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveToHighlights' : ActorMethod<
    [StatusId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchUserByUsername' : ActorMethod<
    [string],
    [] | [{ 'userId' : UserId, 'profile' : UserProfile }]
  >,
  'searchUsers' : ActorMethod<
    [string],
    Array<{ 'userId' : UserId, 'profile' : UserProfile }>
  >,
  'sendMessage' : ActorMethod<[ConversationId, MessageInput], MessageId>,
  'setTypingStatus' : ActorMethod<[ConversationId, boolean], undefined>,
  'transferGold' : ActorMethod<[string, bigint], undefined>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'unfollowChannel' : ActorMethod<[ChannelId], undefined>,
  'unlikeChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'unlikeStatus' : ActorMethod<[StatusId], undefined>,
  /**
   * / Remove the pinned post from a channel.
   * / Only the channel owner may unpin.
   */
  'unpinChannelPost' : ActorMethod<
    [ChannelId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Remove the pinned message from a conversation.
   * / Any conversation member may unpin.
   */
  'unpinMessage' : ActorMethod<
    [ConversationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCallerAvatar' : ActorMethod<[string], undefined>,
  'updateCallerBio' : ActorMethod<[string], undefined>,
  'updateCallerDisplayName' : ActorMethod<[string], undefined>,
  'updateChannel' : ActorMethod<
    [ChannelId, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateGroupAvatar' : ActorMethod<[ConversationId, string], undefined>,
  'updateGroupName' : ActorMethod<[ConversationId, string], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];