/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChannelId = IDL.Nat;
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'other' : IDL.Text,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const ChannelPostContent = IDL.Record({
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Opt(MediaType),
});
export const ChannelPostId = IDL.Nat;
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const StatusContent = IDL.Record({
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Opt(MediaType),
});
export const StatusId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ChannelCommentId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'lastSeen' : Timestamp,
});
export const Channel = IDL.Record({
  'id' : ChannelId,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const ChannelWithMeta = IDL.Record({
  'ownerProfile' : UserProfile,
  'isFollowing' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'channel' : Channel,
});
export const Status = IDL.Record({
  'id' : StatusId,
  'content' : StatusContent,
  'author' : UserId,
  'timestamp' : Timestamp,
});
export const ChannelCommentWithProfile = IDL.Record({
  'id' : ChannelCommentId,
  'text' : IDL.Text,
  'author' : UserProfile,
  'timestamp' : Timestamp,
});
export const ChannelPostInteractions = IDL.Record({
  'likeCount' : IDL.Nat,
  'comments' : IDL.Vec(ChannelCommentWithProfile),
  'likedByMe' : IDL.Bool,
});
export const ChannelPost = IDL.Record({
  'id' : ChannelPostId,
  'content' : ChannelPostContent,
  'channelId' : ChannelId,
  'author' : UserId,
  'timestamp' : Timestamp,
});
export const MessageContent = IDL.Record({
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Opt(MediaType),
});
export const MessageReadReceipt = IDL.Record({
  'userId' : UserId,
  'timestamp' : Timestamp,
});
export const ReplyToInfo = IDL.Record({
  'messageId' : MessageId,
  'preview' : IDL.Text,
  'senderUsername' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : MessageContent,
  'readReceipts' : IDL.Vec(MessageReadReceipt),
  'sender' : UserId,
  'timestamp' : Timestamp,
  'replyTo' : IDL.Opt(ReplyToInfo),
  'reactions' : IDL.Vec(UserId),
});
export const ConversationType = IDL.Variant({
  'group' : IDL.Text,
  'direct' : IDL.Null,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'lastMessageTimestamp' : IDL.Int,
  'members' : IDL.Vec(UserId),
  'messages' : IDL.Vec(Message),
  'type' : ConversationType,
});
export const GoldTxId = IDL.Nat;
export const GoldTxType = IDL.Variant({
  'buyRequest' : IDL.Null,
  'sent' : IDL.Null,
  'claimed' : IDL.Null,
  'received' : IDL.Null,
  'sellRequest' : IDL.Null,
});
export const GoldTransaction = IDL.Record({
  'id' : GoldTxId,
  'timestamp' : Timestamp,
  'txType' : GoldTxType,
  'counterpartyUsername' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const NotificationId = IDL.Nat;
export const NotificationKind = IDL.Variant({
  'goldGifted' : IDL.Record({ 'fromUsername' : IDL.Text, 'amount' : IDL.Nat }),
  'channelPostLiked' : IDL.Record({
    'channelId' : IDL.Nat,
    'byUsername' : IDL.Text,
    'postId' : IDL.Nat,
  }),
  'channelPostCommented' : IDL.Record({
    'channelId' : IDL.Nat,
    'byUsername' : IDL.Text,
    'postId' : IDL.Nat,
  }),
  'storyCommented' : IDL.Record({
    'byUsername' : IDL.Text,
    'statusId' : IDL.Nat,
  }),
  'storyLiked' : IDL.Record({ 'byUsername' : IDL.Text, 'statusId' : IDL.Nat }),
  'channelFollowed' : IDL.Record({
    'channelId' : IDL.Nat,
    'byUsername' : IDL.Text,
  }),
});
export const AppNotification = IDL.Record({
  'id' : NotificationId,
  'kind' : NotificationKind,
  'read' : IDL.Bool,
  'timestamp' : Timestamp,
});
export const StatusCommentWithProfile = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : UserProfile,
  'timestamp' : Timestamp,
});
export const StatusInteractions = IDL.Record({
  'likeCount' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'comments' : IDL.Vec(StatusCommentWithProfile),
  'likedByMe' : IDL.Bool,
});
export const DealerInfo = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const MessageInput = IDL.Record({
  'content' : MessageContent,
  'replyToMessageId' : IDL.Opt(MessageId),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChannelPost' : IDL.Func(
      [ChannelId, ChannelPostContent],
      [ChannelPostId],
      [],
    ),
  'addGroupMember' : IDL.Func([ConversationId, IDL.Text], [], []),
  'addMessageReaction' : IDL.Func([ConversationId, MessageId], [], []),
  'addStatus' : IDL.Func([StatusContent], [StatusId], []),
  'adminClaimGold' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'commentOnChannelPost' : IDL.Func(
      [ChannelPostId, IDL.Text],
      [ChannelCommentId],
      [],
    ),
  'commentOnStatus' : IDL.Func([StatusId, IDL.Text], [CommentId], []),
  'createChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ChannelId],
      [],
    ),
  'createDirectConversation' : IDL.Func([UserId], [ConversationId], []),
  'createGroupConversation' : IDL.Func(
      [IDL.Text, IDL.Vec(UserId), IDL.Opt(IDL.Text)],
      [ConversationId],
      [],
    ),
  'deleteChannel' : IDL.Func([ChannelId], [], []),
  'deleteChannelPost' : IDL.Func([ChannelPostId], [], []),
  'deleteGroupName' : IDL.Func([ConversationId], [], []),
  'deleteHighlight' : IDL.Func([StatusId], [], []),
  'deleteMessage' : IDL.Func([ConversationId, MessageId], [], []),
  'editChannelPost' : IDL.Func([ChannelPostId, ChannelPostContent], [], []),
  'editMessage' : IDL.Func([ConversationId, MessageId, IDL.Text], [], []),
  'followChannel' : IDL.Func([ChannelId], [], []),
  'forwardChannelPost' : IDL.Func(
      [ChannelPostId, ConversationId],
      [MessageId],
      [],
    ),
  'getActiveUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdminTotalClaimed' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllChannels' : IDL.Func([], [IDL.Vec(ChannelWithMeta)], ['query']),
  'getAllStories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([ChannelId], [IDL.Opt(ChannelWithMeta)], ['query']),
  'getChannelPostInteractions' : IDL.Func(
      [ChannelPostId],
      [ChannelPostInteractions],
      ['query'],
    ),
  'getChannelPosts' : IDL.Func([ChannelId], [IDL.Vec(ChannelPost)], ['query']),
  'getChannelsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChannelWithMeta)],
      ['query'],
    ),
  'getContactStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
      ['query'],
    ),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getGroupAvatars' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ConversationId, IDL.Text))],
      ['query'],
    ),
  'getGroupCreators' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ConversationId, UserId))],
      ['query'],
    ),
  'getHighlights' : IDL.Func([UserId], [IDL.Vec(Status)], ['query']),
  'getMessageReactions' : IDL.Func(
      [ConversationId, MessageId],
      [IDL.Vec(UserId)],
      ['query'],
    ),
  'getMessageReadReceipts' : IDL.Func(
      [ConversationId, MessageId],
      [IDL.Opt(IDL.Vec(MessageReadReceipt))],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyBlockedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMyGoldBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyGoldTransactions' : IDL.Func([], [IDL.Vec(GoldTransaction)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
  'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getMyTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(GoldTransaction)],
      ['query'],
    ),
  'getPaginatedMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getStatusInteractions' : IDL.Func(
      [StatusId],
      [StatusInteractions],
      ['query'],
    ),
  'getStoryViewers' : IDL.Func([StatusId], [IDL.Vec(IDL.Text)], ['query']),
  'getStoryViewersList' : IDL.Func([StatusId], [IDL.Vec(IDL.Text)], ['query']),
  'getTotalChannelsCreated' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalGoldVolume' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalStoriesPosted' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadCount' : IDL.Func([ConversationId], [IDL.Nat], ['query']),
  'getUserByPrincipal' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserChannelsCreated' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserStoriesPosted' : IDL.Func([], [IDL.Nat], ['query']),
  'getUsersWithGoldAbove' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DealerInfo)],
      ['query'],
    ),
  'isBlockedBy' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isHighlighted' : IDL.Func([StatusId], [IDL.Bool], ['query']),
  'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'leaveConversation' : IDL.Func([ConversationId], [], []),
  'likeChannelPost' : IDL.Func([ChannelPostId], [], []),
  'likeStatus' : IDL.Func([StatusId], [], []),
  'listUserConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'markAsRead' : IDL.Func([ConversationId], [], []),
  'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'recordStoryView' : IDL.Func([StatusId], [], []),
  'removeFromHighlights' : IDL.Func(
      [StatusId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeGroupMember' : IDL.Func([ConversationId, UserId], [], []),
  'removeMessageReaction' : IDL.Func([ConversationId, MessageId], [], []),
  'requestBuyGold' : IDL.Func([IDL.Nat], [], []),
  'requestSellGold' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveToHighlights' : IDL.Func(
      [StatusId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
      [],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
      ['query'],
    ),
  'sendMessage' : IDL.Func([ConversationId, MessageInput], [MessageId], []),
  'transferGold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'unblockUser' : IDL.Func([UserId], [], []),
  'unfollowChannel' : IDL.Func([ChannelId], [], []),
  'unlikeChannelPost' : IDL.Func([ChannelPostId], [], []),
  'unlikeStatus' : IDL.Func([StatusId], [], []),
  'updateCallerAvatar' : IDL.Func([IDL.Text], [], []),
  'updateCallerBio' : IDL.Func([IDL.Text], [], []),
  'updateCallerDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateChannel' : IDL.Func(
      [ChannelId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateGroupAvatar' : IDL.Func([ConversationId, IDL.Text], [], []),
  'updateGroupName' : IDL.Func([ConversationId, IDL.Text], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChannelId = IDL.Nat;
  const MediaType = IDL.Variant({
    'audio' : IDL.Null,
    'other' : IDL.Text,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const ChannelPostContent = IDL.Record({
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Opt(MediaType),
  });
  const ChannelPostId = IDL.Nat;
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const StatusContent = IDL.Record({
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Opt(MediaType),
  });
  const StatusId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ChannelCommentId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'lastSeen' : Timestamp,
  });
  const Channel = IDL.Record({
    'id' : ChannelId,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const ChannelWithMeta = IDL.Record({
    'ownerProfile' : UserProfile,
    'isFollowing' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'channel' : Channel,
  });
  const Status = IDL.Record({
    'id' : StatusId,
    'content' : StatusContent,
    'author' : UserId,
    'timestamp' : Timestamp,
  });
  const ChannelCommentWithProfile = IDL.Record({
    'id' : ChannelCommentId,
    'text' : IDL.Text,
    'author' : UserProfile,
    'timestamp' : Timestamp,
  });
  const ChannelPostInteractions = IDL.Record({
    'likeCount' : IDL.Nat,
    'comments' : IDL.Vec(ChannelCommentWithProfile),
    'likedByMe' : IDL.Bool,
  });
  const ChannelPost = IDL.Record({
    'id' : ChannelPostId,
    'content' : ChannelPostContent,
    'channelId' : ChannelId,
    'author' : UserId,
    'timestamp' : Timestamp,
  });
  const MessageContent = IDL.Record({
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Opt(MediaType),
  });
  const MessageReadReceipt = IDL.Record({
    'userId' : UserId,
    'timestamp' : Timestamp,
  });
  const ReplyToInfo = IDL.Record({
    'messageId' : MessageId,
    'preview' : IDL.Text,
    'senderUsername' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : MessageContent,
    'readReceipts' : IDL.Vec(MessageReadReceipt),
    'sender' : UserId,
    'timestamp' : Timestamp,
    'replyTo' : IDL.Opt(ReplyToInfo),
    'reactions' : IDL.Vec(UserId),
  });
  const ConversationType = IDL.Variant({
    'group' : IDL.Text,
    'direct' : IDL.Null,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'lastMessageTimestamp' : IDL.Int,
    'members' : IDL.Vec(UserId),
    'messages' : IDL.Vec(Message),
    'type' : ConversationType,
  });
  const GoldTxId = IDL.Nat;
  const GoldTxType = IDL.Variant({
    'buyRequest' : IDL.Null,
    'sent' : IDL.Null,
    'claimed' : IDL.Null,
    'received' : IDL.Null,
    'sellRequest' : IDL.Null,
  });
  const GoldTransaction = IDL.Record({
    'id' : GoldTxId,
    'timestamp' : Timestamp,
    'txType' : GoldTxType,
    'counterpartyUsername' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const NotificationId = IDL.Nat;
  const NotificationKind = IDL.Variant({
    'goldGifted' : IDL.Record({
      'fromUsername' : IDL.Text,
      'amount' : IDL.Nat,
    }),
    'channelPostLiked' : IDL.Record({
      'channelId' : IDL.Nat,
      'byUsername' : IDL.Text,
      'postId' : IDL.Nat,
    }),
    'channelPostCommented' : IDL.Record({
      'channelId' : IDL.Nat,
      'byUsername' : IDL.Text,
      'postId' : IDL.Nat,
    }),
    'storyCommented' : IDL.Record({
      'byUsername' : IDL.Text,
      'statusId' : IDL.Nat,
    }),
    'storyLiked' : IDL.Record({
      'byUsername' : IDL.Text,
      'statusId' : IDL.Nat,
    }),
    'channelFollowed' : IDL.Record({
      'channelId' : IDL.Nat,
      'byUsername' : IDL.Text,
    }),
  });
  const AppNotification = IDL.Record({
    'id' : NotificationId,
    'kind' : NotificationKind,
    'read' : IDL.Bool,
    'timestamp' : Timestamp,
  });
  const StatusCommentWithProfile = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : UserProfile,
    'timestamp' : Timestamp,
  });
  const StatusInteractions = IDL.Record({
    'likeCount' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'comments' : IDL.Vec(StatusCommentWithProfile),
    'likedByMe' : IDL.Bool,
  });
  const DealerInfo = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const MessageInput = IDL.Record({
    'content' : MessageContent,
    'replyToMessageId' : IDL.Opt(MessageId),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChannelPost' : IDL.Func(
        [ChannelId, ChannelPostContent],
        [ChannelPostId],
        [],
      ),
    'addGroupMember' : IDL.Func([ConversationId, IDL.Text], [], []),
    'addMessageReaction' : IDL.Func([ConversationId, MessageId], [], []),
    'addStatus' : IDL.Func([StatusContent], [StatusId], []),
    'adminClaimGold' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'commentOnChannelPost' : IDL.Func(
        [ChannelPostId, IDL.Text],
        [ChannelCommentId],
        [],
      ),
    'commentOnStatus' : IDL.Func([StatusId, IDL.Text], [CommentId], []),
    'createChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ChannelId],
        [],
      ),
    'createDirectConversation' : IDL.Func([UserId], [ConversationId], []),
    'createGroupConversation' : IDL.Func(
        [IDL.Text, IDL.Vec(UserId), IDL.Opt(IDL.Text)],
        [ConversationId],
        [],
      ),
    'deleteChannel' : IDL.Func([ChannelId], [], []),
    'deleteChannelPost' : IDL.Func([ChannelPostId], [], []),
    'deleteGroupName' : IDL.Func([ConversationId], [], []),
    'deleteHighlight' : IDL.Func([StatusId], [], []),
    'deleteMessage' : IDL.Func([ConversationId, MessageId], [], []),
    'editChannelPost' : IDL.Func([ChannelPostId, ChannelPostContent], [], []),
    'editMessage' : IDL.Func([ConversationId, MessageId, IDL.Text], [], []),
    'followChannel' : IDL.Func([ChannelId], [], []),
    'forwardChannelPost' : IDL.Func(
        [ChannelPostId, ConversationId],
        [MessageId],
        [],
      ),
    'getActiveUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdminTotalClaimed' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllChannels' : IDL.Func([], [IDL.Vec(ChannelWithMeta)], ['query']),
    'getAllStories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([ChannelId], [IDL.Opt(ChannelWithMeta)], ['query']),
    'getChannelPostInteractions' : IDL.Func(
        [ChannelPostId],
        [ChannelPostInteractions],
        ['query'],
      ),
    'getChannelPosts' : IDL.Func(
        [ChannelId],
        [IDL.Vec(ChannelPost)],
        ['query'],
      ),
    'getChannelsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChannelWithMeta)],
        ['query'],
      ),
    'getContactStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
        ['query'],
      ),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getGroupAvatars' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ConversationId, IDL.Text))],
        ['query'],
      ),
    'getGroupCreators' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ConversationId, UserId))],
        ['query'],
      ),
    'getHighlights' : IDL.Func([UserId], [IDL.Vec(Status)], ['query']),
    'getMessageReactions' : IDL.Func(
        [ConversationId, MessageId],
        [IDL.Vec(UserId)],
        ['query'],
      ),
    'getMessageReadReceipts' : IDL.Func(
        [ConversationId, MessageId],
        [IDL.Opt(IDL.Vec(MessageReadReceipt))],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyBlockedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMyGoldBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyGoldTransactions' : IDL.Func(
        [],
        [IDL.Vec(GoldTransaction)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
    'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getMyTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(GoldTransaction)],
        ['query'],
      ),
    'getPaginatedMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getStatusInteractions' : IDL.Func(
        [StatusId],
        [StatusInteractions],
        ['query'],
      ),
    'getStoryViewers' : IDL.Func([StatusId], [IDL.Vec(IDL.Text)], ['query']),
    'getStoryViewersList' : IDL.Func(
        [StatusId],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTotalChannelsCreated' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalGoldVolume' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalStoriesPosted' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadCount' : IDL.Func([ConversationId], [IDL.Nat], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserChannelsCreated' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserStoriesPosted' : IDL.Func([], [IDL.Nat], ['query']),
    'getUsersWithGoldAbove' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DealerInfo)],
        ['query'],
      ),
    'isBlockedBy' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isHighlighted' : IDL.Func([StatusId], [IDL.Bool], ['query']),
    'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'leaveConversation' : IDL.Func([ConversationId], [], []),
    'likeChannelPost' : IDL.Func([ChannelPostId], [], []),
    'likeStatus' : IDL.Func([StatusId], [], []),
    'listUserConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'markAsRead' : IDL.Func([ConversationId], [], []),
    'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'recordStoryView' : IDL.Func([StatusId], [], []),
    'removeFromHighlights' : IDL.Func(
        [StatusId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeGroupMember' : IDL.Func([ConversationId, UserId], [], []),
    'removeMessageReaction' : IDL.Func([ConversationId, MessageId], [], []),
    'requestBuyGold' : IDL.Func([IDL.Nat], [], []),
    'requestSellGold' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveToHighlights' : IDL.Func(
        [StatusId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
        [],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
        ['query'],
      ),
    'sendMessage' : IDL.Func([ConversationId, MessageInput], [MessageId], []),
    'transferGold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'unblockUser' : IDL.Func([UserId], [], []),
    'unfollowChannel' : IDL.Func([ChannelId], [], []),
    'unlikeChannelPost' : IDL.Func([ChannelPostId], [], []),
    'unlikeStatus' : IDL.Func([StatusId], [], []),
    'updateCallerAvatar' : IDL.Func([IDL.Text], [], []),
    'updateCallerBio' : IDL.Func([IDL.Text], [], []),
    'updateCallerDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateChannel' : IDL.Func(
        [ChannelId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateGroupAvatar' : IDL.Func([ConversationId, IDL.Text], [], []),
    'updateGroupName' : IDL.Func([ConversationId, IDL.Text], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };